Collect some data (e.g., from a friend or your teammate or from an LLM) on the recognition memory
task from the slides (or construct your own task or simulate the task) and fit the following two models
using Stan:
• The One-High-Threshold Model (1HT)
• The Two-High-Threshold Model (2HT)
The models are depcited on Slide 12 (MPT models). As usual, inspect the convergence of the MCMC
samplers and report the estimation results. Do the two models suggest different estimates for the
two key parameters? Describe and interpret the results.

Hit words:
apple, chair, river, pencil, cloud, bottle, garden, mirror, thunder, carpet, lantern, bridge, feather, window, candle, forest, pillow, rocket, ocean, glove

Test:
carpet, jungle, feather, spoon, river, mirror, ladder, candle, planet, glove, bottle, sunset, thunder, pencil, cactus, ocean, chair, trophy, lantern, flame, apple, crystal, pillow, breeze, forest, window, marble, rocket, shadow, cloud, garden, violin, bridge, copper, thunder, blanket, pillow, compass, candle, stone

Response:
old, new, new, new, old, old, new, new, new, old, old, new, new, old, new, new, old, new, old, new, old, new, new, new, old, new, new, old, new, old, old, new, new, new, old, old, old, new, new, new

In [1]:
import cmdstanpy
from cmdstanpy import CmdStanModel
import numpy as np

c:\Users\David\anaconda3\envs\stan\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [8]:
data = {
    "N_old": 20,
    "N_new": 20,
    "hits": 12,
    "misses": 8,
    "FA": 3,
    "CR":17   
}

In [9]:
model_1HT = cmdstanpy.CmdStanModel(stan_file="./model/1ht.stan")

# Fit model
fit_1HT = model_1HT.sample(
    data=data,
    chains=4,
    iter_warmup=1000,
    iter_sampling=2000,
    seed=42
)

13:04:31 - cmdstanpy - INFO - CmdStan start processing
chain 1:   0%|          | 0/3000 [00:00<?, ?it/s, (Warmup)]





chain 1:  93%|█████████▎| 2800/3000 [00:00<00:00, 27948.19it/s, (Sampling)]
chain 1: 100%|██████████| 3000/3000 [00:00<00:00, 24784.05it/s, (Sampling completed)]
chain 2: 100%|██████████| 3000/3000 [00:00<00:00, 23601.83it/s, (Sampling completed)]

chain 3: 100%|██████████| 3000/3000 [00:00<00:00, 22930.85it/s, (Sampling completed)]




chain 4: 100%|██████████| 3000/3000 [00:00<00:00, 21885.00it/s, (Sampling completed)]

13:04:32 - cmdstanpy - INFO - CmdStan done processing.

In [10]:
fit_1HT.summary()

,Mean,MCSE,StdDev,MAD,5%,50%,95%,ESS_bulk,ESS_tail,ESS_bulk/s,R_hat
lp__,-48.262300,0.016509,1.008520,0.745027,-50.270900,-47.964300,-47.285000,3889.01,5209.26,22610.5,1.00082
d,0.512623,0.001401,0.095551,0.097285,0.349541,0.516727,0.663502,4746.12,4167.48,27593.7,1.00028
g,0.169211,0.000915,0.058060,0.057099,0.084558,0.162504,0.273307,4071.17,4468.77,23669.6,1.00038

In [11]:
model_2HT = cmdstanpy.CmdStanModel(stan_file="./model/2ht.stan")

# Fit model
fit_2HT = model_1HT.sample(
    data=data,
    chains=4,
    iter_warmup=1000,
    iter_sampling=2000,
    seed=42
)

13:04:39 - cmdstanpy - INFO - CmdStan start processing
chain 1:   0%|          | 0/3000 [00:00<?, ?it/s, (Warmup)]


chain 1:  33%|███▎      | 1000/3000 [00:00<00:00, 24643.09it/s, (Sampling)]


chain 1: 100%|██████████| 3000/3000 [00:00<00:00, 27097.85it/s, (Sampling completed)]
chain 2: 100%|██████████| 3000/3000 [00:00<00:00, 26896.28it/s, (Sampling completed)]


chain 3: 100%|██████████| 3000/3000 [00:00<00:00, 25931.74it/s, (Sampling completed)]




chain 4: 100%|██████████| 3000/3000 [00:00<00:00, 25434.57it/s, (Sampling completed)]

13:04:39 - cmdstanpy - INFO - CmdStan done processing.

In [12]:
fit_2HT.summary()

,Mean,MCSE,StdDev,MAD,5%,50%,95%,ESS_bulk,ESS_tail,ESS_bulk/s,R_hat
lp__,-48.262300,0.016509,1.008520,0.745027,-50.270900,-47.964300,-47.285000,3889.01,5209.26,20468.5,1.00082
d,0.512623,0.001401,0.095551,0.097285,0.349541,0.516727,0.663502,4746.12,4167.48,24979.6,1.00028
g,0.169211,0.000915,0.058060,0.057099,0.084558,0.162504,0.273307,4071.17,4468.77,21427.2,1.00038